image: node:16.3.0

# stages:
#  - deploy

# job_deploy:
#   stage: deploy
#   image: docker
#   tags:
#     - front
#   script:
#     - echo 'deploy'
#     - docker build -t container .
#     - if [ $(docker ps -aq --filter name=$CI_PROJECT_NAME) ]; then docker rm -f $CI_PROJECT_NAME;fi
#     - docker run  -p 8086:80 -d  --name $CI_PROJECT_NAME container

# - build
# dependencies:
#   - build
#1

stages:
  - deploy

# build:
#   image: docker/compose:latest
#   stage: build
#   script:
#     - docker-compose build
#   artifacts:
#     paths:
#       - ./
#       - docker-compose.yml

deploy:
  image: docker/compose:latest
  stage: deploy
  before_script:
    - if [[ "$CI_COMMIT_REF_NAME" == "master" ]] || [[ "$CI_COMMIT_REF_NAME" == "main" ]]; then  echo "SELF_DOMAIN_NAME=''" >> .env; else echo "SELF_DOMAIN_NAME=-$CI_COMMIT_REF_NAME" >> .env;  fi;
    - ls -las
    - pwd
    - sed -i  's/servername/'"$CI_COMMIT_REF_NAME"'/g' docker-compose.yaml;
    - cat docker-compose.yaml
  script:
    - docker-compose up -d --build
