image: node:16.3.0

stages:
  - makeLogFile
  - artifacts
  - deploy

makeLogFile:
  stage: makeLogFile
  script:
    - chmod 777 ./depoly/version.sh
    - . ./depoly/version.sh
  interruptible: true

artifacts:
  stage: artifacts
  image: node:16.17.0
  script:
    - npm config set registry http://registry.npm.taobao.org/
    - npm install -g pnpm
    - pnpm config set registry https://registry.npm.taobao.org/
    - pnpm install
    - pnpm run build
  artifacts:
    paths:
      - dist/
    exclude:
      - node_modules/
  cache:
    when: on_success
    key:
      files:
        - pnpm-lock.yaml
        - package.json
  only:
    - main
    - master
  interruptible: true

deploy:
  image: docker/compose:latest
  stage: deploy
  tags:
    - front-docker-1
  before_script:
    - if [[ "$CI_COMMIT_REF_NAME" == "master" ]] || [[ "$CI_COMMIT_REF_NAME" == "main" ]]; then  echo "SELF_DOMAIN_NAME=''" >> .env; else echo "SELF_DOMAIN_NAME=-$CI_COMMIT_REF_NAME" >> .env;  fi;
    - ls -las
    - pwd
    - sed 's/servername/'"$CI_COMMIT_REF_NAME"'/g' docker-compose.yaml >docker-compose-updated.yaml
    - cat docker-compose-updated.yaml
  script:
    - docker-compose -f docker-compose-updated.yaml up -d --build
    - . ./depoly/notification.sh
  environment:
    name: canvas
    url: https://canvas.abclive.cloud
  interruptible: true
