version: '3'
services:
  servername:
    container_name: paint-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
    build:
      context: .
      dockerfile: Dockerfile
    image: paint-${CI_COMMIT_REF_NAME}
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.canvasHttp${SELF_DOMAIN_NAME}.rule=Host(`canvas${SELF_DOMAIN_NAME}.abclive.cloud`)'
      - 'traefik.http.routers.canvasHttp${SELF_DOMAIN_NAME}.entrypoints=web'

      - 'traefik.http.routers.canvasHttps${SELF_DOMAIN_NAME}.rule=Host(`canvas${SELF_DOMAIN_NAME}.abclive.cloud`)'
      - 'traefik.http.routers.canvasHttps${SELF_DOMAIN_NAME}.tls.certresolver=le'
      - 'traefik.http.routers.canvasHttps${SELF_DOMAIN_NAME}.tls=true'
      - 'traefik.http.routers.canvasHttps${SELF_DOMAIN_NAME}.entrypoints=websecure'

      - 'traefik.http.routers.osliveCanvasHttp${SELF_DOMAIN_NAME}.rule=Host(`canvas${SELF_DOMAIN_NAME}.oslive.cloud`)'
      - 'traefik.http.routers.osliveCanvasHttp${SELF_DOMAIN_NAME}.entrypoints=web'
      - 'traefik.http.routers.osliveCanvasHttps${SELF_DOMAIN_NAME}.rule=Host(`canvas${SELF_DOMAIN_NAME}.oslive.cloud`)'
      - 'traefik.http.routers.osliveCanvasHttps${SELF_DOMAIN_NAME}.tls.certresolver=le'
      - 'traefik.http.routers.osliveCanvasHttps${SELF_DOMAIN_NAME}.tls=true'
      - 'traefik.http.routers.osliveCanvasHttps${SELF_DOMAIN_NAME}.entrypoints=websecure'

networks:
  default:
    external:
      name: traefik_default
