version: '3'
services:
  serverName:
    container_name: paint-${CI_COMMIT_REF_NAME}-${CI_COMMIT_SHORT_SHA}
    build:
      context: .
      dockerfile: Dockerfile
    image: paint-${CI_COMMIT_REF_NAME}
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.canvas.rule=Host(`canvas${SELF_DOMAIN_NAME}.abclive.cloud`)'
      - 'traefik.http.routers.canvas.entrypoints=web'

      - 'traefik.http.routers.canvasHttps.rule=Host(`canvas${SELF_DOMAIN_NAME}.abclive.cloud`)'
      - 'traefik.http.routers.canvasHttps.tls.certresolver=le'
      - 'traefik.http.routers.canvasHttps.tls=true'
      - 'traefik.http.routers.canvasHttps.entrypoints=websecure'

networks:
  default:
    external:
      name: traefik_default
